export const menuHeader = [
  {
    text: "Về chúng tôi",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Thông tin du học",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Học bổng",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Academic",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Học tiếng anh",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Việc Làm - Định cư",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
  {
    text: "Cộng đồng",
    child: [
      { text: "Pháp nhân", href: "" },
      { text: "Ban giám đốc", href: "" },
      { text: "Lĩnh vực - Mục tiêu kinh doanh", href: "" },
      { text: "Tôn chỉ làm việc", href: "" },
      { text: "Thành tựu công ty", href: "" },
      { text: "Các văn phòng", href: "" },
      { text: "Nhân viên", href: "" },
      { text: "Giờ làm việc", href: "" },
      { text: "Đức Anh - Cùng thời gian", href: "" },
    ],
  },
];
