export interface ISection2TableData {
  id: number;
  date: string;
  time: string;
  location: string;
  country: string;
  event: string;
  href: string;
}

export const section2TableData: ISection2TableData[] = [
  {
    id: 1,
    date: "24/04/2024",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "Pre-Departure Briefing: Hướng dẫn trước khi bay nhập học",
    href: "/",
  },
  {
    id: 2,
    date: "28/01/2024",
    time: "10h-12h",
    location: "TP.HCM",
    country: "Thụy Sỹ",
    event: "Lên kế hoạch du học & săn học bổng cùng chuyên gia",
    href: "/",
  },
  {
    id: 3,
    date: "20/12/2023",
    time: "10h-12h",
    location: "Hà Nội",
    country: "Úc",
    event: "SYDNEY OPEN DAY - Học bổng tới 50.000 AUD",
    href: "/",
  },
  {
    id: 4,
    date: "19/12/2023",
    time: "10h-12h",
    location: "Vinh",
    country: "Úc",
    event: "Học bổng tới 900 triệu VNĐ từ SEG - Thụy Sĩ",
    href: "/",
  },
  {
    id: 5,
    date: "17/12/2023",
    time: "10h-12h",
    location: "online",
    country: "Đức",
    event: "Gặp gỡ trực tiếp 8 khoa của ĐH Monash",
    href: "/",
  },
  {
    id: 6,
    date: "16/12/2023",
    time: "10h-12h",
    location: "Hà Nội",
    country: "Phần Lan",
    event: "Chiến lược chinh phục Học bổng 20-100% tại Deakin Uni",
    href: "/",
  },
  {
    id: 7,
    date: "16/12/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 8,
    date: "16/12/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 9,
    date: "16/12/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 10,
    date: "16/12/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 11,
    date: "11/11/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 12,
    date: "22/22/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 13,
    date: "33/33/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 14,
    date: "44/44/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 15,
    date: "55/55/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 16,
    date: "66/66/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 17,
    date: "77/77/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 18,
    date: "88/88/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 19,
    date: "99/99/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
  {
    id: 20,
    date: "10/10/2023",
    time: "10h-12h",
    location: "online",
    country: "Nhiều nước",
    event: "UAL #1 về đào tạo Thiết kế- Kiến trúc- Nghệ thuật",
    href: "/",
  },
];
